//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILG_Global.BussinessLogic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ILG_GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ILG_GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ILG_Global.BussinessLogic.Resources.ILG_GlobalResources", typeof(ILG_GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ اثناء حفظ طلبك..
        /// </summary>
        public static string An_Error_has_occurred_while_saving_your_request_ {
            get {
                return ResourceManager.GetString("An Error has occurred while saving your request.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل البريد الالكترونى..
        /// </summary>
        public static string Email_Required_ {
            get {
                return ResourceManager.GetString("Email Required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد الكترونى غير صحيح..
        /// </summary>
        public static string Invalid_Email_Address_ {
            get {
                return ResourceManager.GetString("Invalid Email Address.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد اشتركت في النشرة الإخبارية بنجاح..
        /// </summary>
        public static string You_Subscribed_to_Newsletter_Successfully_ {
            get {
                return ResourceManager.GetString("You Subscribed to Newsletter Successfully.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ طلبك بنجاح.
        /// </summary>
        public static string Your_request_Saved_Successfully_ {
            get {
                return ResourceManager.GetString("Your request Saved Successfully.", resourceCulture);
            }
        }
    }
}
